{ lib, stdenv, gcc, pkgs }:

stdenv.mkDerivation rec {
  pname = "wcwidth-icons";
  version = "0.2.2";

  src = ./.;

  nativeBuildInputs = [ gcc ];

  buildPhase = ''
    LDFLAGS="-Wl,-z,defs -Wl,--no-as-needed"
    CFLAGS="-ldl"
    $CC $LDFLAGS $CFLAGS -shared -fPIC -o libwcwidth-icons.so wcwidth-icons.c
  '';

  installPhase = ''
    install -D libwcwidth-icons.so $out/lib/libwcwidth-icons.so
  '';

  meta = {
    homepage = "https://github.com/powerman/wcwidth-icons";
    license = lib.licenses.lgpl21Plus;
    description = ''
      Support fonts with double-width icons in xterm/rxvt-unicode/zsh/vim/...

      If fonts with icons like Nerd Fonts are used with some terminals like rxvt-unicode
      then icons must have single-width (Nerd Fonts calls this "Mono" font,
      generated by Nerd Fonts Font Patcher with option --use-single-width-glyphs) to work correctly.
      This makes icons too small (about 1/4 of normal size for most icons).

      To fix this for most applications (like xterm/rxvt-unicode/zsh/…) which use
      libc function (like wcwidth(3) or wcswidth(3)) to get symbol width you can use provided library in LD_PRELOAD environment variable.

      To fix some other applications (like vim) you may need to build these applications with extra patch, provided in patches/ directory.

      ```
      export LD_PRELOAD=$${pkg.wcswidth-icons}/lib/libwcwidth-icons.so
      ```
    '';

    platforms = lib.platforms.linux;
  };
}
