# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci"  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.supportedFilesystems = [ "zfs" "ntfs" ];
  networking.hostId = "6e4e3d83"; # Required for zfs
  networking.hostName = "argon";
  boot.kernelPackages = config.boot.zfs.package.latestCompatibleLinuxPackages;
  boot.zfs.requestEncryptionCredentials = true;

  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 20;
  boot.loader.efi.canTouchEfiVariables = true;

  # boot.loader.systemd-boot.enable = true;
  # boot.loader.efi.canTouchEfiVariables = true;
  # boot.loader.grub.splashImage = lib.mkForce ../../../assets/grub/akira.png;
  # boot.loader.grub.backgroundColor = lib.mkForce "#09090B";

  # boot.loader.grub.efiSupport = true;
  # boot.loader.grub.memtest86.enable = true;
  # boot.loader.grub.enable = true;
  # #boot.loader.grub.version = 2;
  # boot.loader.grub.useOSProber = true;
  # boot.loader.grub.devices =
  #   [ "/dev/disk/by-id/nvme-KINGSTON_SKC3000S1024G_50026B7686493B4A" ];

  boot.initrd.postDeviceCommands = lib.mkAfter ''
    # zfs rollback -r tank/system/root@blank
  '';

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
