# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let GBytes = 1073741824;
in {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ehci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelParams = [ "zfs.zfs_recover=1" # TODO: Remove after fixing "PANIC: zfs: adding existent segment to range tree".
                        "zfs.zfs_arc_max=${toString (24 * GBytes)}" ]; # 32GB is too much
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.supportedFilesystems = [ "zfs" "ntfs" ];
  networking.hostId = "b2a1e45e"; # Required for zfs
  networking.hostName = "xenon";
  boot.kernelPackages = pkgs.linuxPackages_zen;
  boot.zfs.package = pkgs.zfs_2_4; # ZFS 2.4 supports kernel 6.18
  boot.zfs.requestEncryptionCredentials = true;

  boot.loader.grub.memtest86.enable = true;
  boot.loader.grub.enable = true;
  boot.loader.grub.useOSProber = true;
  boot.loader.grub.devices =
    [ "/dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S649NF0RB27391E" ];

  boot.initrd.postDeviceCommands = lib.mkAfter ''
    # zfs rollback -r tank/local/blank-root@blank
  '';

  # fileSystems."/" = {
  #   device = "none";
  #   options = [ "defaults" "size=4G" "mode=755" ];
  #   fsType = "tmpfs";
  # };

  # # fileSystems."/" =
  # #   { device = "tank/local/blank-root";
  # #     fsType = "zfs";
  # #     options = [ "nodev" "nosuid" ];
  # #   };

  # fileSystems."/nix" = {
  #   device = "tank/local/nix";
  #   fsType = "zfs";
  #   options = [ "nodev" "nosuid" ];
  # };

  # fileSystems."/var/lib/docker" = {
  #   device = "tank/safe/docker";
  #   fsType = "zfs";
  #   options = [ "nodev" "nosuid" ];
  # };

  # fileSystems."/home" = {
  #   device = "tank/safe/home";
  #   fsType = "zfs";
  #   options = [ "nodev" "nosuid" ];
  # };

  # fileSystems."/persist" = {
  #   device = "tank/safe/persist";
  #   fsType = "zfs";
  #   neededForBoot = true;
  #   options = [ "nodev" "nosuid" ];
  # };

  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/eb5a9586-c8c2-48c4-8615-4a6613aaf3c8";
  #   fsType = "ext4";
  #   options = [ "nodev" "nosuid" "noexec" ];
  # };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
