git clone --depth 1 https://github.com/NeshHari/XMonad.git NeshHari--XMonad 
git clone --depth 1 https://github.com/balsoft/nixos-config.git balsoft--nixos 
git clone --depth 1 https://github.com/vlaci/nixos-config.git vlaci--nixos 
git clone --depth 1 https://gitlab.com/K900/nix.git K900--nix 
git clone --depth 1 https://github.com/Baitinq/nixos-config.git Baitinq--nixos 
git clone --depth 1 https://github.com/vyorkin/nixos-config.git vyorkin--nixos 
git clone --depth 1 https://github.com/Weathercold/nixfiles.git Weathercold--nixfiles 
git clone --depth 1 https://git.sr.ht/~rycee/configurations rycee--configuration 
git clone --depth 1 https://git.azahi.cc/nixfiles git.azahi.cc--nixfile 
git clone --depth 1 https://github.com/nix-community/disko.git nix-community--disko 
git clone --depth 1 https://github.com/Mic92/dotfiles.git Mic92--dotfiles 
git clone --depth 1 https://github.com/setser/nixos-config.git setser--nixos 
git clone --depth 1 https://github.com/zoriya/flake.git zoriya--flake 
git clone --depth 1 https://github.com/wiedzmin/nixos-config.git wiedzmin--nixos 
git clone --depth 1 https://github.com/kanashimia/nixos-config.git kanashimia--nixos 
git clone --depth 1 https://github.com/hlissner/dotfiles hlissner--dotfile 
git clone --depth 1 http://github.com/cab404/nixos-config.git cab404--nixos 
git clone --depth 1 https://github.com/kenranunderscore/dotfiles.git kenranunderscore--dotfiles 
git clone --depth 1 https://github.com/LunNova/nixos-configs LunNova--nixos 
git clone --depth 1 https://github.com/Lord-Valen/configuration.nix.git Lord-Valen--configuration 
git clone --depth 1 https://github.com/jakehamilton/config.git jakehamilton--config 
git clone --depth 1 https://github.com/saksmt/nix-config.git saksmt--nix 
git clone --depth 1 https://bitbucket.org/bzz/nixos.git bzz--nixos 
